# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5750a272b22a9b4d8ed2f19506ddbae03db3db596a2bed1734996fe26864ab36acda3eebaa234eedc82c985efc29007a49c89a2f80cb700bedd0ab456f15f913

test:
  secret_key_base: 89328596536f2d6057f7aa19c491681730b74a0c706bce4f1822c07582f63639903eecb9b5c3d44d0167087813eeb7b0f7be5942fede4d7bf3a568e14af242f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
